title: > 
  <p align="center"> Chandrakant Shinde </p>
logo: /assets/img/profile.jpg
description: > 
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/chandrakant-shinde/">LinkedIn</a> |
  <a href="https://github.com/shinde-chandrakant">GitHub</a>
  <br>As a forward-thinking software engineer with over 1.5 years of experience, I excel at creating innovative software solutions to enhance business productivity. My expertise spans the entire SDLC and project management. I have worked in the financial domain at Genpact, delivering high-quality software solutions..</p>
# show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal
